name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
        working-directory: ./my-app

      - name: Build Next.js app
        run: |
          npm run build
          touch out/.nojekyll  # Prevents GitHub Pages from trying to process files with underscores
        working-directory: ./my-app
        env:
          NEXT_PUBLIC_BASE_PATH: '/${{ github.event.repository.name }}'

      - name: Create 404 page
        run: |
          cp out/404.html out/404.html || cp out/index.html out/404.html
        working-directory: ./my-app

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./my-app/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
