name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js in my-app
        run: |
          cd my-app
          # Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'

      - name: Install dependencies in my-app
        run: |
          cd my-app
          npm install
          # List files to check that we're in the right directory
          ls -alh

      - name: Build in my-app
        run: |
          cd my-app
          npm run build
          npm run export
          # List files after build to confirm output
          ls -alh out

      - name: Fix 404 for GitHub Pages
        run: |
          cp my-app/out/index.html my-app/out/404.html
          # List files after fix
          ls -alh my-app/out

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: my-app/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
